const { ApolloServer, gql, ApolloError, UserInputError } = require('apollo-server');
const express=require('express');
const cors = require('cors');

const app=express();
app.use(cors());

// Mock data
let posts = [
  { id: '1', content: 'Bored Ape Yacht Club (BAYC), often colloquially called Bored Apes or Bored Ape is a non-fungible token (NFT) collection built on the Ethereum blockchain with the ERC-721 standard. The collection features profile pictures of cartoon apes that are procedurally generated by an algorithm.',  username: 'user1', image: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxMHEhUTExIVFhUVFhcWGBUSExMYFREYFxUXGhcXFRcYHSgkGB0lJxYWJTIjJSkrMi4uFyAzODMtOCgtLi0BCgoKDg0OGxAQGi4lICYtLS0vLS0yLS0vLS03LS0yLS83LS0vNS0tLS0uLS0tNS0tLS0tLS01LS0uLS0tLS01Lf/AABEIAKgBLAMBIgACEQEDEQH/xAAbAAEAAgMBAQAAAAAAAAAAAAAABAUCAwYHAf/EADwQAAIBAgQDBgEKBAcBAAAAAAABAgMRBBIhMQVBURMiYXGBkQYUIzJCUqGxssHwYnLC0QcVQ5Ki4fGT/8QAGQEBAAMBAQAAAAAAAAAAAAAAAAMEBQEC/8QAJxEBAAICAgECBQUAAAAAAAAAAAECAxEEITESQRQiMqHwE0JRYZH/2gAMAwEAAhEDEQA/AOfABeZgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYVK0ae7V+nP2EzryREz4Zg0fK4/xf7X+preOVrqMvVW976/cRzmxx+6EsYMk/tlLBXfLJ7uLtyire8nv6JL9CdRqdrFPqrnaZa3+mXL4r0+qGYAPaMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANdep2UW/ZdW9kJnXcuxG51D7UqxpbtLze/kKVaNX6Mk/JrTzNnAPh2tx5ylG6pxeWVTROcucYXava++y211tJ4x8FVMEs9KVTOtUqjTz25RktE/x5lD46ItrXS/8D8vntFNdWqqW+/JLdkSjxD5RHurvLSV07Qf6+XufLW19292SZuXWnVe5R4eHa87t1DOpVlU52XSP6v8AtYUKEqt8kJStvkhKVn45Udf8JfCPyxKtiI9x6wpPTOuUqn8L5R589ND0ClTVFKMUoxSslFJJLwS2M2+S15+aWlSlaRqsPDqi7J2l3X0lo/Zix7FjeK4eEbTnGSeijZT7R/ZitpPw5c7HK4/g1LBQhXlh4OL7OUoKKss+Ji5LKtJWpyaWmuQ8xD16nM8I4FiOMa0qd4r683lhfopfW9E7c7ENQlgakqU1ZqTi19iabv5p/vc9nwlaFeClTacLaZdrdEeSfGVeOHx9a/27pLd/Nw0/5fcS4LzXJGkWesXpMT+SwBCU69SOeNN5bXuqdSSt/Mk7mzB4h1tJJJrXTaSfNfvoalM9LzqJZV+PelfVMJIAJkIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEHG1dfCCu/O36L8xOKriEWu0tvo/RxS/R+xW5czGPpa4cROTt7FwPh3yShTpXcYwik8jcXUna9STa1SzN6K3PfQ24ik5vs4NyX11UblGCezzPvZuaV9lyumTsPVVeMZraUVJPqmk1+Jp4cu63zc6jb8e0kvuSS8ooyNtZ5P8ScBlwPFVG3Fxr/ORyxcdVZT0u97xe+7Zl8MYGPEcXSpyScbuck/rRhFyt4pvKn4NnVf4nJZKD555R9JQu/L6COI4bxN8FxFKulmUG1KKds0ZK0l52d14pHY7PZ6/ieJQp1Oyi4OrlUss6kacYxbaUpylsm4taKT02OQ/xD4fi40oujjFUnK94UoU3T30785pRtr3lG7tyLTEcY4b8Qwip1IOTfcjJNVYy6Qi1du9tFe7S30Iz4RHDtKM8Sk9s3yaMn/9mn9xLS1a+a9/n9Irxaff8/1yvwNiquHw2KhjJS0q4eVN27SpWkql6kFUje91FJOTsnLc9E4vi8PRr4aniW4026lSNoTnFzpqEYRkopq3zravpeK52OcxHwriMVVU39GH0FWxEr3s7ycaUcifpLf1M+I8MqYKrReXPOpmpWlXc6VpK8lOlKnlabjDWOV6LXQ7N4m0W/gisxGlbw7jOK4Vi6k5xfySeepJ1XhoSpaOVowpVJ35Jc7vV73sMH8NrjWLr4qWXJ20oU86cr9n3ZNQ0s8ykrt/V25m/EcLqUIvs6OFeJir04vF1HGE7aSjSqQ0a3SvY6TgVONChThFy+bioSz/AE8yXez/AMTd23zvfVO54vbfenqlZjraPhcD2NSUU4vLkks9OL7ssytfdSvCWuujWh5bjYqljK8Y/RjVrRVtklOOi8np6Ho/H+NLg9OpW/1KlqdGL5qF7TkvspzlLxTit2eZYGOa83rfZveV3eUn/M/wT5kvFrM5I0i5VtY537pYANdjgAAAAAAAAAAAAAAAAAAAAAAAAAAAAARcbD63TSXk+fp+DZKB5vSL1msveO80tFodX8DfE0KdOOGryUHDu05ydozh9WDb2ktlfdW5naZOyu4pvM72TSV+uu3j72vv4vLCW+i7Lo1dLyCoTisqqWj0Skl7ZrGXPDybakcvFMeXV/4hcSpJU6Dmp4iVTPJQ1VOMITWVvlbPtu8zdlc42UVLRmupglRnB3u0pW5JLS9l6r2NpDlpNJ1PlYxXi9dx4TPh3GQ4JiIV5U3NRzXStmWaLWaN9L6+zZ9+JMZQ4zUXY8RqUczfzXyXE55vdtypp536taL1hPQ9R+Dvh2PB6KcoLtp96ba1hfaC6WXTm2eYtruXbQp/hPAY7htNVKmKq1aUf9KvRUJyhzlB55STW6Ukm7W0vcvePxniKtGFKSU+/OLaTUGouOdr61lOTS2zRV9C0oQqRlJTalHKrOyvfNPMmulnD2ZonFQxcH9qhNeHcqU3/X9xz1bnbmunmuP4N/kVftcTV4jVTl9JSo9nJy0WaTqXWrW0dHax02D+KqXZVcRUqOEpVHahBwlOWWEFGzcb6rLeTsl1On4pgYY6FSFSVozhlabVo7uM1faSve/guh45DBdnVqQqJ5oSySi9s0bq/ina6vyaZLjrOWdI8l4x13KVxDGVOP1XWq7PSMFeyitor+H8z120MgDXx46441DIy5bZJ3IAD2jAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBxkrydt1HTzbd/6TGLzJMjYit89JW6NPrlcVNfh7m+nLOtFfolzfJIxuRucktzjajFC8+F+H/K6ud3jCnZ57K2e8csdeet145fJ95DFOUmu8/nHBvlH5vPfy2j5sr+B4OWAo04OOsc0ZvaGZXlKaT1d5WV+ivoiXGnJRy1Zd1Kks17Ock1mb8JPKrc9epDKTbfHFy70U8skkk27xzSvlWu/JvT6yIfF+JSpdlUunKm05W0jlrRlC+a2119xtrVXeSaUpQaqQjG+kX3Yt9XdTfp4GrE0IuDi0oU4KUWnrnpRho1bXuuzXk+pwbp04q6zvdxalZpupNSytNarXL5N8zkfiXB9jW7VNWq9xpcpUrxTvzvFJPo4PqjoeEYjs4W2anlk5apS7TK4X3u9bPZtscbofK6NRJR1fca2lNNS1a1i3KLj46dSXDf0XiUWanrpMOKB8i8yuuZ9NtiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACm43RcOzlHdTk34xnuvvRp4biowxDg75c9GpHK7Nq9O6T5cizxyzOK8Jf0/3KmtgLyb6arqk+X3GZyZj9SYlrcWJ/SiXscqfbOcNWqkbzTdnBShlio6fwy06u4q1YRWaopL5vtHGSbUFRkpXt9pOS88vgclwH4uhiKfY4iTVTu25OcVazptbvS9t73W1mddSrzms0aNaak7603HKsuiipW5pb9WU5iYWdwRmqeinZQqZZ5ldyc1dK/nUg9OljF0JyWS6dotQqvWSeWCTkubbz3tyj4nx1ql43oVnvddlGzd04u+Z2tb7zXOjWlFKnhakZRUpQcp0cqqSjNd5Opdx77Zx1AnPsa7d4xjVjJp2vCcqVlBtdEpxvtrBk3E4pYZSlZQlFVH3m8sU87c6itpGTpafzETjmHeHlSnVq4bCwpznJdvVu5qcJKUclrS1ebSXK1uZC4pUo4yhPNiqtWOq+aw84025rKleo7Sj3uUufI9xG9PMzrbmcKrQjy7q0fLQ2hA3Y6YMzuQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABCxjvOPhGX3uNvyswPmbtZOXXRfyrb8W/UyMXkWi2SZhucas1xREouLwUcSujWqa0cX4MiYWriOHTS7OjUi2rzdO0l4yyOLb8XctTCrHPFpc17Hil9dT4SXpvx5XsOKVqf0Z5UuUZ4mK9lWsSf8AP670lKTXhWrx/qZUUp9qk+qv5eBmavw2Kfb7yx/icse/2hYUuJqk3KOHpKb3k225fzNJN+5px3EKmOspZVFO+WEbJtbNttyfk3bnYig9V4+Os7iHm3IyWjUyAAmQgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANGLxUcIry8kub/fUqquOqVeeVdI6f8ALf8AA8WyRVJTFa3hb18RGh9KSXhzfklqyqxmPWKais0YJ9585adFstfP2IiVv3v5nyUL67Pqv3qQXyTaNLOPDFZ3PayhiIz2d/JO3oZqd+vsyphOVLr5x2fmv/Tcsa1z/wB0f/ChOCfZfjNHusj43Yrvlrf1l6I1zxMpc5P2iv0/U5GCzs5qpc8W8LLuyvHVyj056Pk3/wBlrRxEa/0ZJ+F9V5rkc0qbn9Lb7MdvV8za1cvYrzSNeVHLjjJO46dKChpY2pRtZ5lzUtdPB7p+/kXdGoq0VJbMtVvFlS+OaeWYAPSMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD5J5dXsj6QuLVckMv2nb03f9vU5adRt2tfVOlXiq3yqTk9nok+Uf+9/XwNMNNOn3oyTufJK/mv20U5nc7aMRqNQyB8Ppx0AAAAAAABjU0XqvxRbcGneMo9JX9JL+6kU9WVveP5kWPCJ5ZtdY/len5mSYp1ZFmjdJW4ALSiAAAAAAAAAAAAAAAAAAAAAAAAAAAAABTcVqZ6lvsq3q9X92UAizfSm48fMgU3ZtevuZp3AKy600pZZOPqv1RvAAAAAAAAAAj4lWcX/ABJP30J2ClkqQfjb3TX6oA7XzDzf6ZXwALrOAAAAAAAAAAAAAAAAf//Z', userId: '2', isFollowing: false },
];

let users = [
  { id: '1', username: 'user1', email: 'user1@example.com', following: ['2'] },
  { id: '2', username: 'user2', email: 'user2@example.com', following: [] },
];

// Define your type definitions (schema)
const typeDefs = gql`
  type Post {
    id: ID!
    content: String!
    image: String
    userId: ID!
    isFollowing: Boolean!
    user: User!
  }

  type User {
    id: ID!
    username: String!
    email: String!
    following: [ID!]!
  }

  type Query {
    posts(cursor: String): [Post]
    user(id: ID!): User
    newsFeed: [Post]
    userPosts(userId: ID!): [Post]
  }

  type Mutation {
    followUser(userId: ID!): MutationResponse
    unfollowUser(userId: ID!): MutationResponse
    createPost(content: String!, image: String, userId: ID!): Post
  }

  type MutationResponse {
    success: Boolean!
    message: String!
  }
`;

// Define your resolvers
const resolvers = {
  Query: {
    posts: async (_, { cursor }) => {
      try {
        // Fetch posts from your data source
        return posts;
      } catch (error) {
        throw new ApolloError('Failed to fetch posts');
      }
    },
    user: async (_, { id }) => {
      try {
        // Fetch user by ID from your data source
        return users.find(user => user.id === id);
      } catch (error) {
        throw new UserInputError('User not found');
      }
    },
    newsFeed: async () => {
      try {
        // Fetch news feed posts from your data source
        return posts;
      } catch (error) {
        throw new ApolloError('Failed to fetch news feed');
      }
    },
    userPosts: async (_, { userId }) => {
      try {
        return posts.filter(post => post.userId === userId);
      } catch (error) {
        throw new ApolloError('Failed to fetch user posts');
      }
    },
  },
  Mutation: {
    followUser: async (_, { userId }) => {
      try {
        const user = users.find(user => user.id === '1'); // Assuming user with id '1' is the current user
        if (!user) throw new UserInputError('User not found');
        if (user.following.includes(userId)) throw new UserInputError('Already following this user');
        user.following.push(userId);
        return { success: true, message: 'User followed successfully' };
      } catch (error) {
        throw new ApolloError('Failed to follow user');
      }
    },
    unfollowUser: async (_, { userId }) => {
      try {
        const user = users.find(user => user.id === '1'); // Assuming user with id '1' is the current user
        if (!user) throw new UserInputError('User not found');
        user.following = user.following.filter(id => id !== userId);
        return { success: true, message: 'User unfollowed successfully' };
      } catch (error) {
        throw new ApolloError('Failed to unfollow user');
      }
    },
    createPost: async (_, { content, image, userId }) => {
      try {
        // Implement create post logic
        const newPost = { id: String(posts.length + 1), content, image, userId, isFollowing: false };
        posts.push(newPost);
        return newPost;
      } catch (error) {
        throw new ApolloError('Failed to create post');
      }
    },
  },
  Post: {
    user: (post) => users.find(user => user.id === post.userId),
  },
};

// Create an instance of ApolloServer
const server = new ApolloServer({ typeDefs, resolvers });

// Start the server
server.listen().then(({ url }) => {
  console.log(`🚀 Server ready at ${url}`);

}).catch(error => {
  console.error('Error starting the server:', error);
});